# Generated by Django 4.2.10 on 2025-05-01 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_online', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InterestedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('detection_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('details', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('avatar', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(choices=[('REGULAR', 'Regular User'), ('ADMIN', 'Administrator')], default='REGULAR', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=100)),
                ('details', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='api.user')),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='idx_user_email'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='idx_user_role'),
        ),
        migrations.AddField(
            model_name='monitoreduser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_records', to='api.user'),
        ),
        migrations.AddField(
            model_name='interestedevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event'),
        ),
        migrations.AddField(
            model_name='interestedevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_events', to='api.user'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date'], name='idx_event_date'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category'], name='idx_event_category'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_online'], name='idx_event_is_online'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_by'], name='idx_event_created_by'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date', 'category'], name='idx_event_date_category'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['user_id', 'event_id'], name='idx_user_event_composite'),
        ),
        migrations.AlterUniqueTogether(
            name='userevent',
            unique_together={('user', 'event')},
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['user'], name='idx_activity_user'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['timestamp'], name='idx_activity_timestamp'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['action_type'], name='idx_activity_action_type'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['entity_type'], name='idx_activity_entity_type'),
        ),
        migrations.AddIndex(
            model_name='monitoreduser',
            index=models.Index(fields=['user'], name='idx_monitored_user'),
        ),
        migrations.AddIndex(
            model_name='monitoreduser',
            index=models.Index(fields=['detection_time'], name='idx_monitored_detection_time'),
        ),
        migrations.AddIndex(
            model_name='monitoreduser',
            index=models.Index(fields=['is_active'], name='idx_monitored_is_active'),
        ),
        migrations.AddIndex(
            model_name='interestedevent',
            index=models.Index(fields=['user_id'], name='idx_interested_user'),
        ),
        migrations.AddIndex(
            model_name='interestedevent',
            index=models.Index(fields=['event_id'], name='idx_interested_event'),
        ),
        migrations.AlterUniqueTogether(
            name='interestedevent',
            unique_together={('user', 'event')},
        ),
    ]
