# Generated by Django 5.2.1 on 2025-06-01 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("location", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=100)),
                ("image", models.URLField(blank=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("is_online", models.BooleanField(default=False)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["date"], name="api_event_date_58da15_idx"),
                    models.Index(
                        fields=["is_online"], name="api_event_is_onli_985c29_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("avatar", models.URLField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("password", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Regular User"),
                            ("ADMIN", "Administrator"),
                        ],
                        default="REGULAR",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["email"], name="idx_user_email"),
                    models.Index(fields=["role"], name="idx_user_role"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MonitoredUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                ("detection_time", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("details", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_records",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="idx_monitored_user"),
                    models.Index(
                        fields=["detection_time"], name="idx_monitored_detection_time"
                    ),
                    models.Index(fields=["is_active"], name="idx_monitored_is_active"),
                ],
            },
        ),
        migrations.CreateModel(
            name="InterestedEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.event"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interested_events",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user_id"], name="idx_interested_user"),
                    models.Index(fields=["event_id"], name="idx_interested_event"),
                ],
                "unique_together": {("user", "event")},
            },
        ),
        migrations.CreateModel(
            name="UserActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_type", models.CharField(max_length=50)),
                ("entity_type", models.CharField(max_length=50)),
                ("entity_id", models.CharField(max_length=100)),
                ("details", models.JSONField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="idx_activity_user"),
                    models.Index(fields=["timestamp"], name="idx_activity_timestamp"),
                    models.Index(
                        fields=["action_type"], name="idx_activity_action_type"
                    ),
                    models.Index(
                        fields=["entity_type"], name="idx_activity_entity_type"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.event"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user_id", "event_id"], name="idx_user_event_composite"
                    )
                ],
                "unique_together": {("user", "event")},
            },
        ),
    ]
