# Generated by Django 4.2.10 on 2025-05-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='idx_event_category',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='idx_event_created_by',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='idx_event_date_category',
        ),
        migrations.RemoveIndex(
            model_name='userevent',
            name='idx_user_event_composite',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='api_event_date_58da15_idx',
            old_name='idx_event_date',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='api_event_is_onli_985c29_idx',
            old_name='idx_event_is_online',
        ),
    ]
