# Generated by Django 5.2.1 on 2025-06-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_event_idx_event_category_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="userevent",
            index=models.Index(
                fields=["user_id", "event_id"], name="idx_user_event_composite"
            ),
        ),
    ]
