# Generated by Django 4.2.10 on 2025-05-25 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_event_idx_event_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOTPDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=False)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'totp_device',
            },
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['user_id', 'event_id'], name='idx_user_event_composite'),
        ),
        migrations.AddField(
            model_name='totpdevice',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totp_device', to='api.user'),
        ),
    ]
