version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - CLOUDFLARE_DOMAIN=events-managermpp.pages.dev

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend,192.168.1.5,188.27.132.153,events-managermpp.pages.dev,*.pages.dev
      - CORS_ALLOWED_ORIGINS=https://localhost,https://192.168.1.5,https://188.27.132.153,https://events-managermpp.pages.dev
      - SECURE_SSL_REDIRECT=False
      - SECURE_PROXY_SSL_HEADER=HTTP_X_FORWARDED_PROTO,https
      - USE_HTTPS=True
      - CLOUDFLARE_DOMAIN=events-managermpp.pages.dev
    volumes:
      - ./backend/media:/app/media
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data: